### ISSUE TITLE
extended-bg-position

### ISSUE THREAD

**Issue by l-hammer** [l-hammer/You-need-to-know-css#8]

**Comment by shurong2199** [comment]
```css
div:nth-of-type(2){
    background-origin: content-box;
    margin: 29px 0;
}
```
请问:` margin: 29px 0;` 是否必须，作用是什么呢？
